uint8 MANUAL=0
uint8 OFF=1
uint8 READY=2
uint8 DRIVING=3
uint8 EMERGENCY=4
uint8 FINISH=5
uint8 STANDBY=6

uint8 UNAVAILABLE=0
uint8 ACCELERATION=1
uint8 SKIPAD=2
uint8 TRACKDRIVE=3
uint8 EBS_TEST=4
uint8 INSPECTION=5
uint8 AUTOCROSS=6
uint8 MANUAL_DRIVING=7

float32 velocity_cf
float32 velocity_FL
float32 velocity_FR
float32 velocity_RL
float32 velocity_RR

uint8 mission
uint8 state
uint8 info_emer
bool cubemars_enable
